package br.com.caelum.vraptor.http.route;

import java.text.MessageFormat;
import java.util.EnumSet;

import br.com.caelum.vraptor.resource.HttpMethod;

/**
 * Exception thrown when no routes matching given URI allow given HTTP method.
 *
 * @author Lucas Cavalcanti
 * @author Caio Filipini
 */
public class MethodNotAllowedException extends RuntimeException {

	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = 3864735692068670362L;
	private final EnumSet<HttpMethod> allowed;

	public MethodNotAllowedException(EnumSet<HttpMethod> allowed, HttpMethod requested) {
		super(MessageFormat.format("Method {0} is not allowed for requested URI. Allowed Methods are {1}",
				requested, allowed));
		this.allowed = allowed;
	}

	public EnumSet<HttpMethod> getAllowedMethods() {
		return allowed;
	}

}
