package br.com.caelum.vraptor.http.route;

/**
 * Exception thrown when no routes matching URI are found.
 *
 * @author Lucas Cavalcanti
 * @author Caio Filipini
 */
public class ResourceNotFoundException extends RuntimeException {
	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = 121345908850681707L;

}
