
package br.com.caelum.vraptor.http;

import br.com.caelum.vraptor.resource.ResourceMethod;

/**
 * Creates a dynamic class with fields representing parameter methods for the
 * selected method.
 * @see AbstractTypeCreator
 * @author Guilherme Silveira
 */
public interface TypeCreator {

	/**
	 * Returns a type including a field for each one of the parameters from this
	 * method. It also includes a method which .
	 */
	Class<?> typeFor(ResourceMethod method);

	/**
	 * Returns an instance of type generated by typeFor method, with all provided
	 * parameters included.
	 */
	Object instanceWithParameters(ResourceMethod method, Object... parameters);
}
