\thispagestyle{empty}

\newsavebox{\logovraptor}
\sbox{\logovraptor}{\includegraphics{marca.png}}
\vspace*{2.5cm}
\large \centerline{\bf \usebox{\logovraptor}}

\large
\vspace {1.3 cm}
\centerline{\bf ${book.name}}

\normalsize
\vspace{2 cm}
\centerline{\href{http://vraptor.caelum.com.br}{http://vraptor.caelum.com.br}}
\vspace{0.1cm}
\vspace {0.3 cm}

\vspace{2.5cm}

\normalsize
\vspace {0.5 cm}
\begin{center}

Automatically generated by \href{http://sourceforge.net/projects/tubaina/}{Caelum Objects Tubaina} \\
\today

\end{center}

